# Site settings
title: Alex Cwiek
email: a.i.cwiek@gmail.com
url: https://example.github.io
description: "Very talented full stack developer. Pls gib job."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fff'

# Footer settings
footer: Alex Cwiek

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto:a.i.cwiek@gmail.com
    font: envelope
  - title: twitter
    url: https://twitter.com/AlexCviek
    font: twitter
  - title: linkedin
    font: linkedin
    url: https://www.linkedin.com/in/alex-cwiek-a8b1b9b5/
  - title: github
    url: https://github.com/alexcviek
    font: github

project:
  - title: Epic Slap Battle
  - desc: My first project at WDI
  - title: Aurora Borealis
  - desc: My second project at WDI

# Build settings
markdown: kramdown
permalink: pretty
