# Site settings
title: Alex Cwiek
email: a.i.cwiek@gmail.com
url: https://example.github.io
description: "Full Stack Web Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fff'

# Footer settings
footer: Alex Cwiek

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto:a.i.cwiek@gmail.com
    font: envelope
  - title: linkedin
    font: linkedin
    url: https://www.linkedin.com/in/alexcwiek/
  - title: github
    url: https://github.com/alexcviek
    font: github

project:
  - title: Epic Slap Battle
    technologies: HTML5 | SCSS | jQuery | JavaScript | CSS Animations | Git | GitHub | Gulp
    desc: Single player game made using Front End technologies. Game logic designed by me and put in motion by jQuery, with a bit of CSS Animations. This was the first time I was using SASS and I loved it. The rules of the game are simple - instead of sophisticated weapons, you can just slap the opponent.
    image: /img/project1.png
    github: https://github.com/alexcviek/project-0
    heroku: http://safe-ravine-55690.herokuapp.com/
  - title: Aurora Borealis
    technologies: HTML5 | SCSS | jQuery | JavaScript | CSS Animations | Git | GitHub | Gulp | NPM | Yarn | JSON | AJAX | NodeJS | GoogleMaps API | Facebook oAuth | MongoDB | Express.js | Bcrypt | AWS Image Upload
    desc: Express.js CRUD app. Get the most up to date forecast for Aurora Borealis occurrences , based on chosen location, thanks to an API from ACE Spacecraft and a Google Maps API. If you prefer not to go outside - there is a superb, Instagram - like part of the page made with AWS Image Upload, so you can still see auroras without freezing off outside.
    image: /img/project2.png
    github: https://github.com/alexcviek/project-1
    heroku: https://peaceful-peak-78688.herokuapp.com/
  - title: Clowder
    technologies: HTML5 | SCSS | JavaScript | AngularJS | CSS Animations | Git | GitHub | Gulp | NPM | Yarn | JSON | AJAX | NodeJS | Google Maps API | Meetup API | Facebook oAuth | GitHub oAuth | MongoDB | Express.js | Bcrypt | JSON Web Token | Chai and Mocha Testing | AWS Image Upload
    desc: RESTful app with Express.js Back End, MongoDB database and AngularJS Front End, built as a group project. Based on the idea of sharing and volunteering within your community, Clowder allows users to donate and share unused and excess food and goods for free amongst their community and other users of the app. My main priorities were developing Express.js Back End, authentication and Google Maps API,  but overall I was involved in all parts of the project.
    image: /img/project3.png
    github: https://github.com/alexcviek/project-2-group
    heroku: https://team-sausage.herokuapp.com/
  - title: Adventurefy
    technologies: HTML5 | CSS3 | JavaScript | AngularJS | Git | GitHub | Gulp | Yarn | Bower | JSON | Ruby on Rails 5 | Google Maps API | Facebook oAuth | PostgreSQL | Bcrypt | JSON Web Token | AWS Image Upload
    desc: Final Project built in a team of two. Adventurefy is a Rails application with PostgreSQL database, helping you to find a companion for your travels. Apart from signing up for trips and making plans, the app also returns handy factual information about certain countries such as weather, budget and country info, thanks to requests made to external APIs. Developing this app helped me to get comfortable with AngularJS, as I was responsible mostly for the Front End, styling the app in CSS and Google Maps API.
    image: /img/project4.png
    github: https://github.com/alexcviek/project-3-api
    heroku: https://adventurefy.herokuapp.com/

# Build settings
markdown: kramdown
permalink: pretty
