# Site settings
title: Alex Cwiek
email: a.i.cwiek@gmail.com
url: https://example.github.io
description: "Full stack web developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fff'

# Footer settings
footer: Alex Cwiek

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto:a.i.cwiek@gmail.com
    font: envelope
  - title: twitter
    url: https://twitter.com/AlexCviek
    font: twitter
  - title: linkedin
    font: linkedin
    url: https://www.linkedin.com/in/alex-cwiek-a8b1b9b5/
  - title: github
    url: https://github.com/alexcviek
    font: github

project:
  - title: Epic Slap Battle
    technologies: HTML5 | SCSS | jQuery | JavaScript | CSS Animations | Git | GitHub | Gulp
    desc: Single player game made using Front- End technologies. Game logic designed by me and put in motion by jQuery, with a bit of CSS Animations. Instead of sophisticated weapons, you can just slap the opponent.
    image: /img/project1.png
    github: https://github.com/alexcviek/project-0
    heroku: http://safe-ravine-55690.herokuapp.com/
  - title: Aurora Borealis
    technologies: HTML5 | SCSS | jQuery | JavaScript | CSS Animations | Git | GitHub | Gulp | NPM | Yarn | JSON | AJAX | NodeJS | GoogleMaps API | Facebook oAuth | MongoDB | Express.js | Bcrypt | AWS Image Upload
    desc: Express.js CRUD app. Get the most up to date forecast for Aurora Borealis occurrence, based on chosen location, thanks to API from ACE Spacecraft and Google Maps API. If you prefer not to go outside - there is a superb, Instagram - like part of the page made with AWS Image Upload, so you can still see auroras without freezing off outside.
    image: /img/project1.png
    github: https://github.com/alexcviek/project-1
    heroku: https://peaceful-peak-78688.herokuapp.com/

# Build settings
markdown: kramdown
permalink: pretty
